name: 🛠️ Build Containers

on:
  push:
    branches: [main]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend image
        run: |
          docker build -t altogpt-backend ./backend

      - name: Build frontend image
        run: |
          docker build -t altogpt-frontend ./frontend
